name: ddb_discord_presence plugin build

on: [push]

env:
  ZIG_VERSION: 0.9.1

jobs:
  build_linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Get sha_short
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Download DeaDBeeF header
      run: wget https://raw.githubusercontent.com/DeaDBeeF-Player/deadbeef/1.8/deadbeef.h && mkdir deadbeef && mv deadbeef.h deadbeef/
    - name: Install zig
      run: wget https://ziglang.org/download/0.9.1/zig-linux-x86_64-$ZIG_VERSION.tar.xz -O - | tar -xJ  && mv zig-* zig && export PATH=$PATH:$PWD/zig
    - name: Build ddb_discord_presence
      run: make && mkdir binary && make install PREFIX=./binary
    - name: Build ddb_discord_presence with debugging symbols
      run: make clean && make DEBUG=1 && mkdir binary_debug && make install PREFIX=./binary_debug
    - name: Upload artifact linux-${{ steps.vars.outputs.sha_short }}.zip
      uses: actions/upload-artifact@v1
      with:
        name: linux-${{ steps.vars.outputs.sha_short }}
        path: ./binary
    - name: Upload artifact linux-debug-${{ steps.vars.outputs.sha_short }}.zip
      uses: actions/upload-artifact@v1
      with:
        name: linux-debug-${{ steps.vars.outputs.sha_short }}
        path: ./binary_debug
